### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by moji2002** [boazpoolman/strapi-code-themes#2]
node v16.15.1
Strapi 4.2.2

**Comment by boazpoolman** [comment]
Hey @moji2002 

Thanks for your issue submission.

I believe it's an issue with the documentation.
Since `v1.0.2` of the package I don't have named exports anymore, only 1 default export.

Meaning that you should use the package like so in your `app.js` file:

```
import themes from 'strapi-code-themes';

export default {
  config: {
    theme: {
      colors: themes.shadesOfPurple,
    },
  },
};
```

Could you try that out for me and let me know if it fixes the issue? 🙂

Looking forward to hear from you.

**Comment by moji2002** [comment]
> Hey @moji2002
> 
> Thanks for your issue submission.
> 
> I believe it's an issue with the documentation. Since `v1.0.2` of the package I don't have named exports anymore, only 1 default export.
> 
> Meaning that you should use the package like so in your `app.js` file:
> 
> ```
> import themes from 'strapi-code-themes';
> 
> export default {
>   config: {
>     theme: {
>       colors: themes.shadesOfPurple,
>     },
>   },
> };
> ```
> 
> Could you try that out for me and let me know if it fixes the issue? 🙂
> 
> Looking forward to hear from you.

Yeah it fixes the issue, it looks fantastic 🙂
let me fork and change the doc

**Comment by boazpoolman** [comment]
Great! Thanks @moji2002.

The MR is merged.
